-- V10: cycle-7 persistent typed rule registry (item E — RUL-01/RUL-05 groundwork).
--   Single source of truth for rules: the scheduler reads active (enabled, not paused) rows and the
--   dispatch eligibility guard reads revision/pause from the SAME table. Typed/bounded fields only;
--   no arbitrary code/SQL/expression. Immutable monotonic revision bumped on edit. Nothing here
--   activates an asset operationally.

CREATE TABLE rule_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         BIGINT        NOT NULL DEFAULT 0,
    rule_id         VARCHAR(100)  NOT NULL,
    ticker          VARCHAR(20)   NOT NULL,
    comparator      VARCHAR(8)    NOT NULL,
    threshold       NUMERIC(19,6) NOT NULL,
    price_precision INTEGER       NOT NULL,
    hysteresis      NUMERIC(19,6) NOT NULL,
    revision        BIGINT        NOT NULL DEFAULT 1,
    enabled         BOOLEAN       NOT NULL DEFAULT TRUE,
    paused          BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ   NOT NULL,
    updated_at      TIMESTAMPTZ   NOT NULL,
    CONSTRAINT uq_rule_def_rule_id UNIQUE (rule_id),
    CONSTRAINT ck_rule_def_threshold_pos CHECK (threshold > 0),
    CONSTRAINT ck_rule_def_hysteresis_nonneg CHECK (hysteresis >= 0),
    CONSTRAINT ck_rule_def_precision CHECK (price_precision BETWEEN 0 AND 10)
);
