-- V12: cycle-8 durable append-only external-attempt ledger (review P1-high / item C).
--   One row per EXTERNAL submission attempt, created when SENDING commits (not on claim). A proof-gated
--   requeue produces a NEW row on the next send; prior rows are immutable, so attempt history is fully
--   reconstructable. Unique per (outbox_id, claim_generation). No payload/secret stored.

CREATE TABLE outbox_attempt (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outbox_id            BIGINT       NOT NULL,
    logical_key          VARCHAR(200) NOT NULL,
    claim_generation     BIGINT       NOT NULL,
    fencing_token        BIGINT       NOT NULL,
    started_at           TIMESTAMPTZ  NOT NULL,
    finished_at          TIMESTAMPTZ,
    outcome              VARCHAR(20),
    provider_message_id  VARCHAR(120),
    provider_accepted_at TIMESTAMPTZ,
    sanitized_status     VARCHAR(200),
    CONSTRAINT uq_outbox_attempt UNIQUE (outbox_id, claim_generation),
    CONSTRAINT fk_outbox_attempt_outbox FOREIGN KEY (outbox_id) REFERENCES alert_outbox (id)
);

CREATE INDEX ix_outbox_attempt_outbox ON outbox_attempt (outbox_id, started_at);
