-- Cycle-11 item G: append-only ADMIN MUTATION AUDIT LEDGER.
-- Answers "who changed what, when, with what outcome" for every admin command. Insert-only in
-- application code; no row is ever updated or deleted at runtime. Reusable by a future authenticated
-- WhatsApp-command application service (same mechanism, not a bypass). It stores NO secret: no
-- password/hash, no Authorization header, no CSRF token, no Brapi/WAHA credential, no arbitrary payload.

CREATE TABLE admin_audit_event (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    actor            VARCHAR(100) NOT NULL,            -- authenticated principal name (never a credential)
    action           VARCHAR(32)  NOT NULL,            -- CREATE_RULE | EDIT_RULE | SELECT_MODE | PAUSE | RESUME | DISABLE
    rule_id          VARCHAR(100),                     -- nullable for a non-rule action
    before_revision  BIGINT,                           -- nullable
    after_revision   BIGINT,                           -- nullable
    outcome          VARCHAR(24)  NOT NULL,            -- SUCCESS | NO_OP | REJECTED_CONFLICT | REJECTED_VALIDATION | ERROR
    detail           VARCHAR(400),                     -- sanitized, bounded reason; never a secret/payload
    correlation_id   VARCHAR(100),                     -- sanitized request/correlation id when available

    CONSTRAINT ck_admin_audit_action CHECK (action IN
        ('CREATE_RULE','EDIT_RULE','SELECT_MODE','PAUSE','RESUME','DISABLE')),
    CONSTRAINT ck_admin_audit_outcome CHECK (outcome IN
        ('SUCCESS','NO_OP','REJECTED_CONFLICT','REJECTED_VALIDATION','ERROR'))
);

CREATE INDEX ix_admin_audit_occurred ON admin_audit_event (occurred_at);
CREATE INDEX ix_admin_audit_rule     ON admin_audit_event (rule_id, occurred_at);

-- Cycle-11 item F: bounded "latest observation" access pattern (used by the admin latest-quote read,
-- replacing an unbounded full-list load). The existing ix_qobs_ticker_src covers (requested_ticker,
-- source_time); add the receipt-time ordering index the latest-quote query actually sorts on.
CREATE INDEX ix_qobs_ticker_receipt ON quote_observation (requested_ticker, receipt_time);
