-- Cycle-16 (FIN-01/FIN-03): CONSUMER-side provenance for an imported ANALYTICS SNAPSHOT.
-- These tables record WHAT snapshot was imported, by WHOM, WHEN, and its validation outcome, plus the
-- per-asset typed indicator/context the snapshot carried. This is CONTEXT only — it authorizes no asset,
-- enables no worker, and changes no rule decision. No private-portfolio data is stored (FIN-04): there is
-- no column for XIRR, holdings, quantities, cash flows, cost basis or broker identifiers, and the importer
-- refuses a payload that smuggles them. Payload/provenance are bounded; no raw document blob is stored.

CREATE TABLE analytics_snapshot (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id       VARCHAR(200) NOT NULL,            -- producer-assigned logical id (unique)
    schema_version    VARCHAR(100) NOT NULL,            -- must be the supported consumer schema
    producer          VARCHAR(200) NOT NULL,
    producer_version  VARCHAR(200) NOT NULL,
    generated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,  -- producer wall-clock
    market_as_of      DATE NOT NULL,                    -- trading date the analytics describe
    timezone          VARCHAR(100),
    source_id         VARCHAR(200),                     -- provenance / source identifier
    checksum          VARCHAR(64)  NOT NULL,            -- SHA-256 (lowercase hex) of canonical records
    record_count      INTEGER      NOT NULL,
    imported_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    imported_by       VARCHAR(100) NOT NULL,            -- authenticated admin principal (never a credential)
    status            VARCHAR(40)  NOT NULL,            -- CONSUMER_VERIFIED_SYNTHETIC

    CONSTRAINT uq_analytics_snapshot_id UNIQUE (snapshot_id),
    CONSTRAINT ck_analytics_status CHECK (status IN ('CONSUMER_VERIFIED_SYNTHETIC'))
);

CREATE INDEX ix_analytics_snapshot_imported ON analytics_snapshot (imported_at);
CREATE INDEX ix_analytics_snapshot_market   ON analytics_snapshot (market_as_of);

CREATE TABLE analytics_context (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_fk     BIGINT NOT NULL,
    ticker          VARCHAR(20) NOT NULL,              -- trusted-catalog ticker (validated on import)
    as_of           DATE,                              -- completed-bar date this row describes
    -- typed daily indicators (IND-01/02/04/05); nullable, each with its own readiness
    sma20           NUMERIC(20,8),  sma20_readiness   VARCHAR(16),
    sma50           NUMERIC(20,8),  sma50_readiness   VARCHAR(16),
    rsi14           NUMERIC(20,8),  rsi14_readiness   VARCHAR(16),
    ema9            NUMERIC(20,8),  ema9_readiness    VARCHAR(16),
    ema21           NUMERIC(20,8),  ema21_readiness   VARCHAR(16),
    volume_ratio    NUMERIC(20,8),  volume_ratio_readiness VARCHAR(16),
    -- FIN-02 contextual metrics serialized as a bounded, sanitized compact string (name=value:units:readiness#...)
    context_metrics VARCHAR(2000),
    quality         VARCHAR(200),
    status          VARCHAR(40),

    CONSTRAINT fk_analytics_context_snapshot FOREIGN KEY (snapshot_fk)
        REFERENCES analytics_snapshot (id) ON DELETE CASCADE
);

CREATE INDEX ix_analytics_context_snapshot ON analytics_context (snapshot_fk);
CREATE INDEX ix_analytics_context_ticker   ON analytics_context (ticker, as_of);

-- Extend the admin-audit action vocabulary with the snapshot import (same append-only ledger, V13).
ALTER TABLE admin_audit_event DROP CONSTRAINT ck_admin_audit_action;
ALTER TABLE admin_audit_event ADD CONSTRAINT ck_admin_audit_action CHECK (action IN
    ('CREATE_RULE','EDIT_RULE','SELECT_MODE','PAUSE','RESUME','DISABLE','IMPORT_SNAPSHOT'));
