-- Cycle-18 (FIN-01/FIN-03): tighten the analytics-snapshot consumer schema.
--   A) document_digest — SHA-256 of the EXACT imported bytes, so idempotency/conflict bind the WHOLE
--      document (envelope + records), not just the records checksum. V14 rows never stored the raw bytes,
--      so this column is NULLABLE and legacy rows keep NULL (an honest "unknown" — never a fabricated digest).
--   F) numeric columns widened to NUMERIC(24,12) to EXACTLY match the validator's accepted scale/precision
--      (scale<=12, precision<=24) — no silent rounding on persistence.
--   G) FIN-02 context metrics moved to a STRUCTURED child table so every validated field (incl. quality)
--      round-trips losslessly; the old bounded compact string column is dropped.

ALTER TABLE analytics_snapshot ADD COLUMN document_digest VARCHAR(64);   -- nullable; NULL for legacy V14 rows
CREATE INDEX ix_analytics_snapshot_docdigest ON analytics_snapshot (document_digest);

-- F) widen indicator columns to NUMERIC(24,12) (was NUMERIC(20,8)). H2 + PostgreSQL both accept this.
ALTER TABLE analytics_context ALTER COLUMN sma20        TYPE NUMERIC(24,12);
ALTER TABLE analytics_context ALTER COLUMN sma50        TYPE NUMERIC(24,12);
ALTER TABLE analytics_context ALTER COLUMN rsi14        TYPE NUMERIC(24,12);
ALTER TABLE analytics_context ALTER COLUMN ema9         TYPE NUMERIC(24,12);
ALTER TABLE analytics_context ALTER COLUMN ema21        TYPE NUMERIC(24,12);
ALTER TABLE analytics_context ALTER COLUMN volume_ratio TYPE NUMERIC(24,12);

-- G) structured, lossless FIN-02 context metrics (replaces the compact context_metrics string).
CREATE TABLE analytics_context_metric (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analytics_context_fk BIGINT NOT NULL,
    name                 VARCHAR(200) NOT NULL,            -- nonblank; unique within a context row
    metric_value         NUMERIC(24,12),
    units                VARCHAR(200),
    readiness            VARCHAR(16),
    quality              VARCHAR(200),

    CONSTRAINT fk_acm_context FOREIGN KEY (analytics_context_fk)
        REFERENCES analytics_context (id) ON DELETE CASCADE,
    CONSTRAINT uq_acm_context_name UNIQUE (analytics_context_fk, name)
);

CREATE INDEX ix_acm_context ON analytics_context_metric (analytics_context_fk);

ALTER TABLE analytics_context DROP COLUMN context_metrics;
