-- V1: durable alert outbox. Owned by Flyway; JPA validates against this schema.
CREATE TABLE alert_outbox (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logical_key        VARCHAR(200) NOT NULL,
    rule_id            VARCHAR(100) NOT NULL,
    ticker             VARCHAR(20)  NOT NULL,
    message            VARCHAR(1000) NOT NULL,
    state              VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    delivery_confirmed BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_outbox_logical_key UNIQUE (logical_key)
);

CREATE INDEX ix_outbox_state ON alert_outbox (state);
