-- V2: immutable quote observations. Insert-only; market source time kept separate from receipt.
CREATE TABLE quote_observation (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider          VARCHAR(20)  NOT NULL,
    requested_ticker  VARCHAR(20)  NOT NULL,
    returned_ticker   VARCHAR(40)  NOT NULL,
    currency          VARCHAR(8),
    price             NUMERIC(19,6),
    previous_close    NUMERIC(19,6),           -- date/basis intentionally NOT stored (UNKNOWN)
    source_time       TIMESTAMPTZ,             -- market/source time; NULL => ineligible
    receipt_time      TIMESTAMPTZ  NOT NULL,
    provider_stale    BOOLEAN      NOT NULL DEFAULT FALSE,
    eligible          BOOLEAN      NOT NULL,
    rejection_reasons VARCHAR(400)
);

CREATE INDEX ix_qobs_ticker_src ON quote_observation (requested_ticker, source_time);
CREATE INDEX ix_qobs_receipt    ON quote_observation (receipt_time);
