-- V3: durable rule lifecycle state (CROSSING baseline/arm/latch survives restart).
CREATE TABLE rule_state (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id        VARCHAR(100) NOT NULL,
    phase          VARCHAR(20)  NOT NULL DEFAULT 'UNBASELINED',
    rule_revision  BIGINT       NOT NULL DEFAULT 1,
    episode_epoch  BIGINT       NOT NULL DEFAULT 0,
    last_fired_at  TIMESTAMPTZ,
    CONSTRAINT uq_rule_state_rule UNIQUE (rule_id),
    CONSTRAINT ck_rule_phase CHECK (phase IN ('UNBASELINED','ARMED','LATCHED'))
);
