-- V4: cycle-3 reliability additions (independent review P0-1/P0-2/P1).
--   * alert_outbox: lease/fencing/attempts/version for the post-commit claiming dispatcher.
--   * rule_state:   optimistic-lock version + last_processed_source_time for replay/ordering.
--   * brapi_quota:  persistent conservative admission counter.

ALTER TABLE alert_outbox ADD COLUMN fencing_token BIGINT      NOT NULL DEFAULT 0;
ALTER TABLE alert_outbox ADD COLUMN claimed_by    VARCHAR(80);
ALTER TABLE alert_outbox ADD COLUMN lease_until   TIMESTAMPTZ;
ALTER TABLE alert_outbox ADD COLUMN attempts      INTEGER     NOT NULL DEFAULT 0;
ALTER TABLE alert_outbox ADD COLUMN version       BIGINT      NOT NULL DEFAULT 0;

CREATE INDEX ix_outbox_lease ON alert_outbox (state, lease_until);

ALTER TABLE rule_state ADD COLUMN version                    BIGINT      NOT NULL DEFAULT 0;
ALTER TABLE rule_state ADD COLUMN last_processed_source_time TIMESTAMPTZ;

CREATE TABLE brapi_quota (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version              BIGINT      NOT NULL DEFAULT 0,
    cycle_key            VARCHAR(32) NOT NULL,
    hard_limit           INTEGER     NOT NULL DEFAULT 15000,
    routine_ceiling      INTEGER     NOT NULL DEFAULT 10500,
    consumed             INTEGER     NOT NULL DEFAULT 0,
    shared_usage_unknown BOOLEAN     NOT NULL DEFAULT TRUE,
    blocked_until        TIMESTAMPTZ,
    CONSTRAINT uq_brapi_quota_cycle UNIQUE (cycle_key),
    CONSTRAINT ck_brapi_ceiling CHECK (routine_ceiling <= hard_limit)
);
